### ISSUE TITLE
Exception on PyCharm launch

### ISSUE THREAD

**Issue by ant-druha** [ant-druha/PowerShell#1]
Moved from https://bitbucket.org/adernov/powershell/issues/24/exception-on-pycharm-launch

I get an exception with the following stacktrace on launching PyCharm 2018.2.2:
```
java.lang.Throwable: Error reading/parsing session details file /Users/me/Library/Application Support/PyCharm2018.2/PowerShell/lib/LanguageHost/sessions/PSES-IJ-1534967299157-session.info: java.lang.NullPointerException
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.EditorServicesLanguageHostStarter.readSessionFile(EditorServicesLanguageHostStarter.kt:244)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.EditorServicesLanguageHostStarter.startServerSession(EditorServicesLanguageHostStarter.kt:190)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.EditorServicesLanguageHostStarter.establishConnection(EditorServicesLanguageHostStarter.kt:103)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.LanguageServerEndpoint.scheduleStart(LanguageServerEndpoint.kt:249)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.LanguageServerEndpoint.checkStarted(LanguageServerEndpoint.kt:218)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.LanguageServerEndpoint.connectEditor(LanguageServerEndpoint.kt:113)
	at com.intellij.plugin.powershell.lang.lsp.LSPInitMain$Companion$editorOpened$1.run(LSPInitMain.kt:89)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ant-druha** [comment]
Fixed in 2.0.0
